version: '3.8'

services:
  binance_bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - API_KEY=your_api_key_here
      - API_SECRET=your_api_secret_here
    restart: unless-stopped
    command: python bot.py

networks:
  default:
    driver: bridge